console.log("20"+5);
console.log("20"-5);
console.log("20"*5);
console.log("20"/5);
console.log(true+10);
console.log(false+4);

a=Number("69");
console.log(a);
b=Number("Hello")
console.log(b);
c=String(123);
console.log(typeof c);
d=String(true);
console.log(typeof d);
e=Boolean(0);
console.log(e);
f=Boolean(1);
console.log(f);
g=Boolean("");
console.log(g);
h=Boolean("Ajay");
console.log(h);
i=Boolean("WERTYUIO");
console.log(i);
j=Boolean('');
console.log(j);
console.log(parseInt("69.420"));
console.log(parseInt("Hello"));
console.log(parseFloat("69.420"));